a=input("emset chie ?")
b=input("familit chie?")
c=input("chand salete?")
d=input("khodet ro bishtar moarefi kon!")
f=open("info.txt","a")
f.write(a+"\n")
f.write(b+"\n")
f.write(c+"\n")
f.write(d+"\n")
f.close()