from pynput import mouse , keyboard
import time
print("ye gesmat neveshtani ro entekhab kon")
time.sleep(10)
k = keyboard.Controller()
k.press("k")
k.press("h")
k.press("o")
k.press("s")
k.press("h")
k.press("e")
k.press("t")
k.press("o")
k.press("o")
k.press("m")
k.press("a")
k.press("d")
k.press("b")
k.press("e")
k.press("j")
k.press("a")
k.press("y")
k.press("t")
k.press("o")
k.press("n")
k.press("e")
k.press("v")
k.press("e")
k.press("s")
k.press("h")
k.press("t")
k.press("a")
k.press("m")
k.press("?")

