import turtle
turtle.pencolor("light green")
turtle.left(90)
turtle.forward(100)
turtle.bgcolor("light green")
turtle.begin_fill()
turtle.color("green")
turtle.circle(150)
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.end_fill()
turtle.color("white")
turtle.begin_fill()
turtle.circle(130)
turtle.end_fill()
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.end_fill()
turtle.color("red")
turtle.begin_fill()
turtle.circle(110)
turtle.end_fill()


turtle.done()